"""
This type stub file was generated by pyright.
"""

from ctypes import Structure, c_ulonglong

"""
This type stub file was generated by pyright.
"""
class udev(Structure):
    """
    Dummy for ``udev`` structure.
    """
    ...


udev_p = ...
class udev_enumerate(Structure):
    """
    Dummy for ``udev_enumerate`` structure.
    """
    ...


udev_enumerate_p = ...
class udev_list_entry(Structure):
    """
    Dummy for ``udev_list_entry`` structure.
    """
    ...


udev_list_entry_p = ...
class udev_device(Structure):
    """
    Dummy for ``udev_device`` structure.
    """
    ...


udev_device_p = ...
class udev_monitor(Structure):
    """
    Dummy for ``udev_device`` structure.
    """
    ...


udev_monitor_p = ...
class udev_hwdb(Structure):
    """
    Dummy for ``udev_hwdb`` structure.
    """
    ...


udev_hwdb_p = ...
dev_t = c_ulonglong
SIGNATURES = ...
ERROR_CHECKERS = ...
