"""
This type stub file was generated by pyright.
"""

import builtins
import inspect
import linecache
import logging
import os
import io
import pdb
import subprocess
import sys
import time
import traceback
import warnings
import psutil
import tracemalloc
from asyncio import iscoroutinefunction
from contextlib import contextmanager
from functools import partial, wraps
from types import coroutine
from signal import SIGKILL
from multiprocessing import Pipe, Process
from IPython.core.magic import Magics, line_cell_magic, magics_class
from argparse import ArgumentParser, REMAINDER

"""Profile the memory usage of a Python program"""
_CLEAN_GLOBALS = ...
__version__ = ...
_CMD_USAGE = ...
if sys.platform == "win32":
    ...
else:
    ...
_TWO_20 = ...
has_tracemalloc = ...
class MemitResult:
    """memit magic run details.

    Object based on IPython's TimeitResult
    """
    def __init__(self, mem_usage, baseline, repeat, timeout, interval, include_children) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class MemTimer(Process):
    """
    Fetch memory consumption from over a time interval
    """
    def __init__(self, monitor_pid, interval, pipe, backend, max_usage=..., *args, **kw) -> None:
        ...
    
    def run(self): # -> None:
        ...
    


def memory_usage(proc=..., interval=..., timeout=..., timestamps=..., include_children=..., multiprocess=..., max_usage=..., retval=..., stream=..., backend=..., max_iterations=...):
    """
    Return the memory usage of a process or piece of code

    Parameters
    ----------
    proc : {int, string, tuple, subprocess.Popen}, optional
        The process to monitor. Can be given by an integer/string
        representing a PID, by a Popen object or by a tuple
        representing a Python function. The tuple contains three
        values (f, args, kw) and specifies to run the function
        f(*args, **kw).
        Set to -1 (default) for current process.

    interval : float, optional
        Interval at which measurements are collected.

    timeout : float, optional
        Maximum amount of time (in seconds) to wait before returning.

    max_usage : bool, optional
        Only return the maximum memory usage (default False)

    retval : bool, optional
        For profiling python functions. Save the return value of the profiled
        function. Return value of memory_usage becomes a tuple:
        (mem_usage, retval)

    timestamps : bool, optional
        if True, timestamps of memory usage measurement are collected as well.

    include_children : bool, optional
        if True, sum the memory of all forked processes as well

    multiprocess : bool, optional
        if True, track the memory usage of all forked processes.

    stream : File
        if stream is a File opened with write access, then results are written
        to this file instead of stored in memory and returned at the end of
        the subprocess. Useful for long-running processes.
        Implies timestamps=True.

    backend : str, optional
        Current supported backends: 'psutil', 'psutil_pss', 'psutil_uss', 'posix', 'tracemalloc'
        If `backend=None` the default is "psutil" which measures RSS aka "Resident Set Size". 
        For more information on "psutil_pss" (measuring PSS) and "psutil_uss" please refer to:
        https://psutil.readthedocs.io/en/latest/index.html?highlight=memory_info#psutil.Process.memory_full_info 

    max_iterations : int
        Limits the number of iterations (calls to the process being monitored). Relevant
        when the process is a python function.

    Returns
    -------
    mem_usage : list of floating-point values
        memory usage, in MiB. It's length is always < timeout / interval
        if max_usage is given, returns the two elements maximum memory and
        number of measurements effectuated
    ret : return value of the profiled function
        Only returned if retval is set to True
    """
    ...

class _TimeStamperCM:
    """Time-stamping context manager."""
    def __init__(self, timestamps, filename, backend, timestamper=..., func=..., include_children=...) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    


class TimeStamper:
    """ A profiler that just records start and end execution times for
    any decorated function.
    """
    def __init__(self, backend, include_children=...) -> None:
        ...
    
    def __call__(self, func=..., precision=...): # -> Callable[..., Any]:
        ...
    
    def timestamp(self, name=...): # -> _TimeStamperCM:
        """Returns a context manager for timestamping a block of code."""
        ...
    
    def add_function(self, func): # -> None:
        ...
    
    def wrap_function(self, func): # -> Callable[..., Any]:
        """ Wrap a function to timestamp it.
        """
        ...
    
    @contextmanager
    def call_on_stack(self, func, *args, **kwds): # -> Generator[Any, Any, None]:
        ...
    
    def show_results(self, stream=...): # -> None:
        ...
    


class CodeMap(dict):
    def __init__(self, include_children, backend) -> None:
        ...
    
    def add(self, code, toplevel_code=...): # -> None:
        ...
    
    def trace(self, code, lineno, prev_lineno): # -> None:
        ...
    
    def items(self): # -> Generator[tuple[Any, Generator[tuple[Any, Any], None, None]], Any, None]:
        """Iterate on the toplevel code blocks."""
        ...
    


class LineProfiler:
    """ A profiler that records the amount of memory for each line """
    def __init__(self, **kw) -> None:
        ...
    
    def __call__(self, func=..., precision=...): # -> Callable[..., Awaitable[Any]] | Callable[..., Any]:
        ...
    
    def add_function(self, func): # -> None:
        """ Record line profiling information for the given Python function.
        """
        ...
    
    def wrap_function(self, func): # -> Callable[..., Awaitable[Any]] | Callable[..., Any]:
        """ Wrap a function to profile it.
        """
        ...
    
    def runctx(self, cmd, globals, locals): # -> Self:
        """ Profile a single executable statement in the given namespaces.
        """
        ...
    
    def enable_by_count(self): # -> None:
        """ Enable the profiler if it hasn't been enabled before.
        """
        ...
    
    def disable_by_count(self): # -> None:
        """ Disable the profiler if the number of disable requests matches the
        number of enable requests.
        """
        ...
    
    def trace_memory_usage(self, frame, event, arg): # -> Callable[..., ...]:
        """Callback for sys.settrace"""
        ...
    
    def trace_max_mem(self, frame, event, arg): # -> Callable[..., TraceFunction] | Callable[..., ...]:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    
    def enable(self): # -> None:
        ...
    
    def disable(self): # -> None:
        ...
    


def show_results(prof, stream=..., precision=...): # -> None:
    ...

@magics_class
class MemoryProfilerMagics(Magics):
    @line_cell_magic
    def mprun(self, parameter_s=..., cell=...): # -> LineProfiler | None:
        """ Execute a statement under the line-by-line memory profiler from the
        memory_profiler module.

        Usage, in line mode:
          %mprun -f func1 -f func2 <statement>

        Usage, in cell mode:
          %%mprun -f func1 -f func2 [statement]
          code...
          code...

        In cell mode, the additional code lines are appended to the (possibly
        empty) statement in the first line. Cell mode allows you to easily
        profile multiline blocks without having to put them in a separate
        function.

        The given statement (which doesn't require quote marks) is run via the
        LineProfiler. Profiling is enabled for the functions specified by the -f
        options. The statistics will be shown side-by-side with the code through
        the pager once the statement has completed.

        Options:

        -f <function>: LineProfiler only profiles functions and methods it is told
        to profile.  This option tells the profiler about these functions. Multiple
        -f options may be used. The argument may be any expression that gives
        a Python function or method object. However, one must be careful to avoid
        spaces that may confuse the option parser. Additionally, functions defined
        in the interpreter at the In[] prompt or via %run currently cannot be
        displayed.  Write these functions out to a separate file and import them.

        One or more -f options are required to get any useful results.

        -T <filename>: dump the text-formatted statistics with the code
        side-by-side out to a text file.

        -r: return the LineProfiler object after it has completed profiling.

        -c: If present, add the memory usage of any children process to the report.
        """
        ...
    
    @line_cell_magic
    def memit(self, line=..., cell=...): # -> MemitResult | None:
        """Measure memory usage of a Python statement

        Usage, in line mode:
          %memit [-r<R>t<T>i<I>] statement

        Usage, in cell mode:
          %%memit [-r<R>t<T>i<I>] setup_code
          code...
          code...

        This function can be used both as a line and cell magic:

        - In line mode you can measure a single-line statement (though multiple
          ones can be chained with using semicolons).

        - In cell mode, the statement in the first line is used as setup code
          (executed but not measured) and the body of the cell is measured.
          The cell body has access to any variables created in the setup code.

        Options:
        -r<R>: repeat the loop iteration <R> times and take the best result.
        Default: 1

        -t<T>: timeout after <T> seconds. Default: None

        -i<I>: Get time information at an interval of I times per second.
            Defaults to 0.1 so that there is ten measurements per second.

        -c: If present, add the memory usage of any children process to the report.

        -o: If present, return a object containing memit run details

        -q: If present, be quiet and do not output a result.

        Examples
        --------
        ::

          In [1]: %memit range(10000)
          peak memory: 21.42 MiB, increment: 0.41 MiB

          In [2]: %memit range(1000000)
          peak memory: 52.10 MiB, increment: 31.08 MiB

          In [3]: %%memit l=range(1000000)
             ...: len(l)
             ...:
          peak memory: 52.14 MiB, increment: 0.08 MiB

        """
        ...
    
    @classmethod
    def register_magics(cls, ip): # -> None:
        ...
    


def load_ipython_extension(ip): # -> None:
    """This is called to load the module as an IPython extension."""
    ...

def profile(func=..., stream=..., precision=..., backend=...): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Awaitable[Any]] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], Awaitable[Any] | Any] | Callable[..., ...]:
    """
    Decorator that will run the function and print a line-by-line profile
    """
    ...

def choose_backend(new_backend=...): # -> str:
    """
    Function that tries to setup backend, chosen by user, and if failed,
    setup one of the allowable backends
    """
    ...

def exec_with_profiler(filename, profiler, backend, passed_args=...): # -> None:
    ...

def run_module_with_profiler(module, profiler, backend, passed_args=...): # -> None:
    ...

class LogFile:
    """File-like object to log text using the `logging` module and the log
    report can be customised."""
    def __init__(self, name=..., reportIncrementFlag=...) -> None:
        """
        :param name: name of the logger module
               reportIncrementFlag: This must be set to True if only the steps
               with memory increments are to be reported

        :type self: object
              name: string
              reportIncrementFlag: bool
        """
        ...
    
    def write(self, msg, level=...): # -> None:
        ...
    
    def flush(self): # -> None:
        ...
    


if __name__ == '__main__':
    parser = ...
    args = ...
    target = args.program[0]
    script_args = args.program[1]
    _backend = ...
