"""
This type stub file was generated by pyright.
"""

from pyudev._errors import DeviceNotFoundAtPathError, DeviceNotFoundByFileError, DeviceNotFoundByNameError, DeviceNotFoundByNumberError, DeviceNotFoundError, DeviceNotFoundInEnvironmentError
from pyudev._util import udev_version
from pyudev.core import Context, Enumerator
from pyudev.device import Attributes, Device, Devices, Tags
from pyudev.discover import DeviceFileHypothesis, DeviceNameHypothesis, DeviceNumberHypothesis, DevicePathHypothesis, Discovery
from pyudev.monitor import Monitor, MonitorObserver
from pyudev.version import __version__, __version_info__

"""
This type stub file was generated by pyright.
"""
